name: Day
author: Liveset1
version: 1.0.1
api: 3.0.0
main: Day\Main.

commands:
  day:
    description: "Make it Day"
permissions:
  day.command:
    default: true
  day.other:
    default: true
